### ISSUE TITLE
Wrong preview gif url

### ISSUE THREAD

**Issue by nryumin** [moussetc/mattermost-plugin-giphy#49] opened 2021-12-24 16:02 UTC
Image src attribute in preview mode is wrong and different from url in final message.

Here it is `/static/files/82c53ca565ed83a033dfb4284740873d.png`
<img width="409" alt="Снимок экрана 2021-12-24 в 18 59 00" src="https://user-images.githubusercontent.com/11360805/147363493-f287ac6f-f3c6-4d56-886e-10629025ea3a.png">

And here is `https://chat.com/api/v4/image?url=https%3A%2F%2Fthumbs.gfycat.com%2FWellinformedRewardingArrowworm-max-1mb.gif`
<img width="504" alt="Снимок экрана 2021-12-24 в 19 01 33" src="https://user-images.githubusercontent.com/11360805/147363547-82fcbc8a-1a5a-44a7-81ea-2108d427c30b.png">

**Comment by moussetc** [comment] 2022-01-04 17:58
Hi, I can't reproduce this issue, so unless you provide more information as asked when creating the issue, I can't help you.

In your case, the most relevant information listing is:

**Mattermost information**
- server version (e.g. 5.20.1)
- client version (e.g. Desktop Client 4.4, or Android app 1.29.0)
- plugin version (e.g. 2.1.0)
- add any relevant server logs (after removing any private data from the logs, such as your IP). They can be found in the Admin console > Server Logs.

**Comment by moussetc** [comment] 2022-07-15 21:36
Hi, I'm closing this issue as it's been 6months+ without further posts. Don't hesitate to comment again it you have more information the issue :)

**Closed by moussetc** 2022-07-15 21:36 UTC
